[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:gateway"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
